#!/bin/sh
# usage: script/bootstrap
#
# install dependencies and generate user related directories

gem install sass

npm install -g npm

npm instal -g docpad

docpad install coffeescript

docpad install sass

docpad install eco
